name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: rust-lang/actions-rust@v1
        with:
          rust-version: stable

      - name: Build project
        run: cargo build --release

      - name: Run tests
        run: cargo test
