name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

# Install system dependencies required by Ruffle Desktop
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev \
            libxcb-shape0-dev \
            libxcb-xfixes0-dev \
            libgtk-3-dev \
            libudev-dev \
            libxcb-xinput-dev \
            libxcb-xkb-dev \
            libxcb-cursor-dev \
            default-jre-headless \
            cmake \
            g++

      # Clone the Ruffle repository (if needed)
      - name: Clone Ruffle repository
        run: |
          git clone https://github.com/ruffle-rs/ruffle.git  --depth=1
          cd ruffle

      # Build and run the ruffle_desktop package
      - name: Build and run Ruffle Desktop
        run: |
          cd ruffle  # Ensure you're in the ruffle directory
          cargo build --release --package=ruffle_desktop
          mkdir -p package/ruffle
          mkdir -p package/extras
          cp target/release/ruffle_desktop package/ruffle/
          cp desktop/packages/linux/rs.ruffle.Ruffle.desktop package/extras/
          cp desktop/packages/linux/rs.ruffle.Ruffle.metainfo.xml package/extras/
          cp desktop/packages/linux/rs.ruffle.Ruffle.svg package/extras/
          cd package
          tar -czvf ../ruffle-linux-package.tar.gz *
          
          
      # Upload the tarball as an artifact
      - name: Upload Release Tarball
        uses: actions/upload-artifact@v4
        with:
          name: ruffle-linux-package
          path: ruffle-linux-package.tar.gz

          
